### ISSUE TITLE
Support sorting yaml files

### ISSUE THREAD

**Issue by luminoso** [Gudahtt/prettier-plugin-sort-json#106]
Hello and thank you for this plugin!

Since YAML is a superset of JSON, is it possible for this plugin to also support yaml files?

**Comment by Gudahtt** [comment]
Thanks for the suggestion! I'm not sure that would be feasible though, as this plugin is essentially a wrapper around the JSON parser provided by Prettier. YAML sorting might be better off as a separate plugin. I'd encourage you to fork this library and give it a shot though! Maybe Prettier's YAML parser works similarly to the JSON one.

**Comment by Gudahtt** [comment]
I'm going to close this for now but please let me know in a reply if you find some other solution for this, or if you try forking this library. I'd be happy to link a YAML sorting plugin from the README.
