### ISSUE TITLE
Usage of `jsonRecursiveSort` in `prettierrc` seems to have no effect

### ISSUE THREAD

**Issue by mjsteinbaugh** [Gudahtt/prettier-plugin-sort-json#145]
Hi @Gudahtt ,

I'm attempting to set recursive sorting of JSON files by default, but I can't seem to get this to work with my `prettierrc` configuration correctly.

For reference, running `prettier --json-recursive-sort file.json` does work as expected.

I've tried both of these configs, to no effect:

```json
{
  "jsonRecursiveSort": true
}
```

```json
{
  "overrides": [
    {
      "files": "*.json",
      "options": {
        "jsonRecursiveSort": true,
        "parser": "json",
        "plugins": ["prettier-plugin-sort-json"]
      }
    }
  ]
}
```

Best,
Mike

**Comment by Gudahtt** [comment]
Thanks for the report!

I've tried reproducing this but haven't succeeded so far. I tried with a file called `.prettierrc.yml` in the root of my project, with the contents:

```
singleQuote: true
trailingComma: all
jsonRecursiveSort: true
```

What was your file called? If it was `prettierrc` (without the leading period), Prettier may not be reading it. See the configuration file documentation for more information: https://prettier.io/docs/en/configuration.html

**Comment by mjsteinbaugh** [comment]
Thanks @Gudahtt I'll try with YAML and see if that works tomorrow

**Comment by mjsteinbaugh** [comment]
Just updated to prettier 3.0.0, will reopen if this issue persists

**Comment by llllvvuu** [comment]
For me on v3.0.0 nothing happens either with the flag or the `.prettierrc.json`. But this could be due to [no Prettier v3 support](https://github.com/Gudahtt/prettier-plugin-sort-json/issues/119)
