### ISSUE TITLE
[feature request] Sorting dependent on arbitrary conditions

### ISSUE THREAD

**Issue by hyperupcall** [Gudahtt/prettier-plugin-sort-json#175]
Thanks for this! We use this at [schemastore](https://github.com/schemastore/schemastore) to better sort schema files.

~~Feature request to change the sorting algorithm based on the name of the property. In other words, a custom `jsonSortOrder` for properties with a particular name.~~

This is a feature request to change the sorting algorithm based on arbitrary conditions. For example, with the following example, I would like to sort stuff in `"properties"` differently.

```json
{
    "type": "object",
    "properties": {
      "a": null,
      "b": null
    }
}
```

Specifically, for all nodes, I would like to sort with a configuration like so:

```json
{
    "type": null,
    "properties": null
}
```

But, if I come across `obj.properties`, I would like to sort if alphabetically, but _only if_ `obj.type === "object" && typeof obj.properties === "object" && obj.properties !== null'`.

A hypothetically configuration could look like the following:

```json
{
  "type": null,
  "properties": null,
  "_custom": [
    {
      "condition": "obj.type === 'object' && typeof obj.properties === 'object' && obj.properties !== null",
      "sort": {
        "/^[^\\d+]/": "lexical"
      }
    }
  ]
}
```

**Comment by Gudahtt** [comment]
Thanks for the suggestion! Could you clarify what this might look like, maybe with an example?

The `json-sort-order` configuration option does already allow changing the sorting algorithm based upon the key: https://github.com/Gudahtt/prettier-plugin-sort-json#json-sort-order

**Comment by hyperupcall** [comment]
Oops! :facepalm: Yeah fixed my issue and added examples

**Comment by Gudahtt** [comment]
Ahhh interesting! Thanks for clarifying, I understand now.

This seems like it could get complicated; I'd rather avoid turning the configuration for this plugin into a programming language itself :sweat_smile:. Lots more to worry about then; validation, performance, security, error handling, etc. But it would also be great to support this use case. I will think on this a bit more.

**Comment by hyperupcall** [comment]
OMG you're right - it would significantly expand the scope of the code. As you alude to, it may be better for things to be in code:

```js
// jsonSortAlgorithmFile.js

/** @returns {Record<PropertyKey, string> | undefined} **/
export function chooseSort(currentNode) {
  if (currentNode.type === 'object' && typeof currentNode.properties === 'object' && currentNode.properties !== null) {
    return {
        "/^[^\\d+]/": "lexical"
    }
  }
}
```

If no object is returned, fallback to the sorting defined by `jsonSortOrder`.

And, instead of the `_custom` shennanigans, only have a single key specifying where to import this file

```json
{
  "jsonSortAlgorithmFile": "jsonSortAlgorithmFile.js"
}
```

I saw in some of your others PRs, the `jsonSortOrder` used to have a feature that parsed a JSON file for the custom sort order, but that was removed due to poor performance. I'm not sure how significant the performance was, but maybe it's something to remember since we would be importing from another file.

**Comment by hyperupcall** [comment]
So I made a quick and dirty [branch](https://github.com/Gudahtt/prettier-plugin-sort-json/compare/main...fox-forks:prettier-plugin-sort-json:hyperupcall-conditional-sorting?expand=1), and this type of thing does not seem straightfoward.

I realized that the ast's are printed like so:

```text
ast ae {
  type: 'ObjectExpression',
  start: 0,
  end: 165,
  loc: ie {
    start: F { line: 1, column: 0, index: 0 },
    end: F { line: 12, column: 1, index: 165 },
    filename: undefined,
    identifierName: undefined
  },
  range: [ 0, 165 ],
  properties: [
    ae {
      type: 'ObjectProperty',
      start: 4,
      end: 17,
      loc: [ie],
      range: [Array],
      method: false,
      key: [ae],
      computed: false,
      shorthand: false,
      value: [ae]
    },
    ae {
      type: 'ObjectProperty',
      start: 21,
      end: 34,
      loc: [ie],
      range: [Array],
      method: false,
      key: [ae],
      computed: false,
      shorthand: false,
      value: [ae]
    },
    ae {
      type: 'ObjectProperty',
      start: 38,
      end: 51,
      loc: [ie],
      range: [Array],
      method: false,
      key: [ae],
      computed: false,
      shorthand: false,
      value: [ae]
    },
    ae {
      type: 'ObjectProperty',
      start: 55,
      end: 68,
      loc: [ie],
      range: [Array],
      method: false,
      key: [ae],
      computed: false,
      shorthand: false,
      value: [ae]
    },
    ae {
      type: 'ObjectProperty',
      start: 72,
      end: 163,
      loc: [ie],
      range: [Array],
      method: false,
      key: [ae],
      computed: false,
      shorthand: false,
      value: [ae]
    }
  ],
  errors: []
}
```

```json5
// test.json
{
  "1b": "value",
  "1a": "value",
  "1c": "value",
  "1d": "value",
  "reverse": {
    "2b": "value",
    "2a": "value",
    "2c": "value",
    "2d": "value"
  }
}
```

Each one is `ObjectExpression` or `ObjectProperty`, and since there is no `node.parent`, it seems impossible to get the context required to make a decision on what to sort...

**Comment by Gudahtt** [comment]
>I saw in some of your others PRs, the jsonSortOrder used to have a feature that parsed a JSON file for the custom sort order, but that was removed due to poor performance. I'm not sure how significant the performance was, but maybe it's something to remember since we would be importing from another file.

Ah, apologies for not providing much detail in that PR ([here](https://github.com/Gudahtt/prettier-plugin-sort-json/pull/118)). Really the unreliable path resolution was what motivated moving away from a dedicated sort options file. See more on that here: https://github.com/Gudahtt/prettier-plugin-sort-json/issues/117#issuecomment-1334738313

**Comment by hyperupcall** [comment]
Thanks for the clarification, that does make sense¶

If it's okay, I'm going to close this issue as I no longer wish to request this feature. Especially since it would be difficult to do so with the current implementation
