### ISSUE TITLE
[feature request] Implement "skip" sort option

### ISSUE THREAD

**Issue by hyperupcall** [Gudahtt/prettier-plugin-sort-json#176]
Sometimes, I want to be able to only move certain properties to the top or bottom. Example:

**Before**

```json
{
  "whateverA": 1,
  "whateverC": 2,
  "whateverB": 3,
  "$schema": 4,
}
```

**After**

```json
{
  "$schema": 4,
  "whateverA": 1,
  "whateverC": 2,
  "whateverB": 3,
}
```

Currently, this is not possible. Some sorter must be used (`null` defaults to `"lexical"`).

**Comment by Gudahtt** [comment]
Thanks again for the contribution @hyperupcall ! This has been released as v3.1.0
