### ISSUE TITLE
jsonSortOrder not working properly?

### ISSUE THREAD

**Issue by x1c0** [Gudahtt/prettier-plugin-sort-json#230]
Hi there, this is my `.prettierrc.js` file

```
module.exports = {
    semi: true,
    trailingComma: 'es5',
    singleQuote: true,
    printWidth: 140,
    tabWidth: 4,
    useTabs: false,
    endOfLine: 'auto',
    plugins: ['prettier-plugin-sort-json'],
    jsonRecursiveSort: true,
    jsonSortOrder: 'caseInsensitiveLexical',
};
```
and when I run this on this json:
```
{
    "a": "a",
    "AB": "AB",
    "b": {
        "e": "ff",
        "c": "dd",
        "a": "b"
    },
    "c": "c"
}
```
I get:
```
{
    "AB": "AB",
    "a": "a",
    "b": {
        "e": "ff",
        "c": "dd",
        "a": "b"
    },
    "c": "c"
}
```
So I see 2 problems here:
1. `jsonSortOrder` is not working since `AB` should not come before `a` because is not using `caseInsensitiveLexical` and is using the default `lexical`
2. `jsonRecursiveSort` is also not working since inside of `b` the json is not being sorted

Thank you

**Comment by Gudahtt** [comment]
Thanks for the report! I am not able to reproduce the bug though. When I try, I get this error:

```
example-prettier-plugin-sort-json git:(main) yarn prettier ./src/example.json
src/example.json
[error] src/example.json: Error: Failed to parse sort order option as JSON
[error]     at Object.parse (...)
```

See here: bda3268b4bd039b4b55d634f1c51482ea1b5c428


The `jsonSortOrder` entry should be a JSON string, like this for example: `jsonSortOrder: '{"*": "caseInsensitiveLexical"}',`.

See https://github.com/Gudahtt/example-prettier-plugin-sort-json/commit/e9922a604f439ec90cc2d96e2a122f0823425375

**Comment by Gudahtt** [comment]
I will close for now and assume it was a misunderstanding, but let me know if that is not the case, or if you have any further feedback/suggestions
