### ISSUE TITLE
Add option to ignore case sensitivity

### ISSUE THREAD

**Issue by eliott-playplay** [Gudahtt/prettier-plugin-sort-json#53]
If we want `{common: "stuff", Demo: "other stuff"}` to be sorted in that order

**Comment by Gudahtt** [comment]
Thanks for the suggestion! Sorry this was mistakenly closed, this isn't possible yet.

**Comment by Gudahtt** [comment]
This is now supported in v0.0.3 by the `jsonSortOrder` configuration. You can try it by creating a sort order JSON file like this:

```json
{
  "/.+/i": "caseInsensitiveLexical"
}
```

Then set the `jsonSortOrder` to the path for that file. Then you should get case-insensitive sorting! Let me know what you think.
