### ISSUE TITLE
how to actually use it?

### ISSUE THREAD

**Issue by hyusetiawan** [Gudahtt/prettier-plugin-sort-json#55]
I am guessing that we need to add it to our .prettierrc? Here is mine below

```
{
  "semi": true,
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": true,
  "printWidth": 160,
  "trailingComma": "all",
  "plugins": ["prettier-plugin-sort-json"]
}
```
in VSCode, object like these:
```
const test = {
  b: 1,
  z: 2,
  a: 11,
}
```
are not sorted on save

**Comment by alifsabrani** [comment]
From [Prettier Offical](https://prettier.io/docs/en/plugins.html), it says:

> Plugins are automatically loaded if you have them installed in the same node_modules directory where prettier is located. Plugin package names must start with @prettier/plugin- or prettier-plugin- or @<scope>/prettier-plugin- to be registered.

I've also tried using this plugin on TS project, but it does not seem to work. All it does was sort .prettierc config.

**Comment by lensbart** [comment]
It’s meant for JSON files, not for JavaScript/TypeScript. That’s why it doesn’t work on `const test = ...` above. See https://github.com/leo-buneev/eslint-plugin-sort-keys-fix instead.

**Comment by Gudahtt** [comment]
Thanks @alifsabrani and @lensbart ! Together you have correctly answered the question.

I will update the README to include clearer instructions. I'll leave this issue open to track that work.

**Comment by lensbart** [comment]
I’d think that having JSON in the package name would be sufficiently explanatory 😅

**Comment by Gudahtt** [comment]
The README has been updated in #97. Please make a new issue if you find anything else confusing. Thanks!
